trigger:
- '*'

variables:
    wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
    dotnetSdkVersion: '6.x'

stages:
- stage: 'Build application'
  displayName: 'Build the web application'
- template: build.yml
  parameters:
    buildConfiguration: 'Release'

- stage: 'Deploy application'
  displayName: 'Deploy the web application'
  dependsOn: Build
- template: deploy.yml
  parameters:
    buildConfiguration: 'Release'