trigger:
- '*'

stages:
- stage: 'Build'
  displayName: 'Build the web application'
- template: build.yml
  parameters:
    buildConfiguration: 'Release'

- stage: 'Deploy'
  displayName: 'Deploy the web application'
  dependsOn: Build
- template: deploy.yml
  parameters:
    buildConfiguration: 'Release'